name               = "alislam-qa"
main               = "src/index.ts"
compatibility_date = "2025-06-27"


[[containers]]
name          = "cloudflare-container-demo"
class_name    = "MainAppContainer"
image         = "./server/Dockerfile"
max_instances = 5
instance_type = "standard"

[[durable_objects.bindings]]
name       = "MAIN_APP_CONTAINER"
class_name = "MainAppContainer"

[[migrations]]
tag                = "v1"
new_sqlite_classes = ["MainAppContainer"]