name = "alislam-qa"
main = "server/dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

# You should set these as secrets instead of vars for security
# Run: wrangler secret put GEMINI_API_KEY
# Run: wrangler secret put PINECONE_API_KEY
# Run: wrangler secret put PINECONE_INDEX

[env.production.vars]
NODE_ENV = "production"

# Assets configuration for serving static frontend files
[assets]
directory = "./client/dist"
binding = "ASSETS"

[triggers]
crons = [] 