version: "3.8"

services:
  embedding-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/home/app/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/app/.cache/huggingface
    volumes:
      # Mount a volume for model caching to avoid re-downloading
      - model_cache:/home/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache:
